modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mcprotector"
version="0.1.0"
displayName="MC Protector"
authors="OpenAI"
description='''Faction claims and protection with Dynmap integration.'''

[[dependencies.mcprotector]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mcprotector]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"
